# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: abctechnologies
  template:
    metadata:
      labels:
        app: abctechnologies
    spec:
      containers:
      - name: abctechnologies
        image: sayednaushadh/abctechnologies:latest  # Update image if needed
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: default
spec:
  selector:
    app: abctechnologies
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: NodePort
